### ISSUE TITLE
Aospless mesa build failed

### ISSUE THREAD

**Issue by asuka-mio** [GloDroid/aospext#11]
See https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25410
[build.tar.gz](https://github.com/GloDroid/aospext/files/12747008/build.tar.gz)
Btw I'm using latest Arch Linux

**Comment by rsglobal** [comment]
Thanks. I use clang-15 and have no such issue.

From meson-log.txt:
```
Command line: `/home/tarsin/Downloads/aospless/toolchain_wrapper/wrap_c /home/tarsin/Downloads/aospless/build/meson-private/tmptipbcfzv/testfile.c -o /home/tarsin/Downloads/aospless/build/meson-private/tmptipbcfzv/output.obj -c '[C_ARGS]' -D_FILE_OFFSET_BITS=64 -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=c11` -> 1
stderr:
clang: error: the flag '-enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang' has been deprecated and will be ignored [-Werror,-Wunused-command-line-argument]
-----------
Checking whether type "struct stat" has member "st_birthtimespec.tv_nsec" : NO 
Running compile:
Working directory:  /home/tarsin/Downloads/aospless/build/meson-private/tmp6uvaz390
Code:
 #include <sys/stat.h>
        void bar(void) {
            struct stat foo;
            foo.st_mtimespec.tv_nsec;

        }
-----------
```

Looks like `-enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang` is causing this issues. 

Please remove this flag from all files in ./toolchain_wrapper/ directory.

ADD:
And do clean rebuild. `make cleanup && make install`

**Comment by asuka-mio** [comment]
Thanks, IMapper4 API works,
No more disjoint planes

**Comment by rsglobal** [comment]
I noticed a [[DNM] Fix aospless build](https://github.com/asuka-mio/mesa/commit/45928618457f3e80f7f832e91e82d2f9b3798e52) commit in your chain. Is it still required?

**Comment by asuka-mio** [comment]
> I noticed a [[DNM] Fix aospless build](https://github.com/asuka-mio/mesa/commit/45928618457f3e80f7f832e91e82d2f9b3798e52) commit in your chain. Is it still required?

Yup, libxml missing readline header

**Comment by rsglobal** [comment]
Okay. It probably can be fixed by installing system libxml-dev or something like that.

**Comment by ilhan-athn7** [comment]
> Okay. It probably can be fixed by installing system libxml-dev or something like that.

Hi, i am getting file not found error even through i have `/usr/include/readline/readline.h` on my archlinux setup.
I use same [build.tar.gz](https://github.com/GloDroid/aospext/files/12747008/build.tar.gz) linked above as workdir.
How should i fix it ?

**Comment by rsglobal** [comment]
Hi,

Try this: https://stackoverflow.com/questions/23085076/readline-readline-h-file-not-found

**Comment by ilhan-athn7** [comment]
> Hi,
> 
> Try this: https://stackoverflow.com/questions/23085076/readline-readline-h-file-not-found

Thanks for the reply, i just built using ndk instead using aospless builder.

**Comment by ilhan-athn7** [comment]
I have tried appending `-I/usr/include/readline` to the files of `toolchain_wrapper` directory.
I think it is a weird idea, yet it does not change anything.
